#!/usr/bin/env bash
# TIER-C11 · CLOSE ACTS — run by the OPERATOR.
# Generated by scripts/tierc11_close.py (do not hand-edit; re-run the generator instead).
#
# Why a script: the acts that publish (the push, publish()) are the operator's; the executor stages them.
#
# Order (each step checked; the script stops at the first failure and says where):
#   0  preconditions: right branch; TC10's CLOSE has run AND is committed (its report tracked in
#      exchange/reports, its STATUS block committed on LEDGER_APOLLO — the ledger keeps tier order); clean
#      index; the CLOSE files present and committed; destinations absent; the stamp pending; F-LAR11 re-run on
#      the pre-stamp append (every «cite» against its source as it stands NOW) — all before anything is pushed
#   1  push the committed work FIRST, before anything changes (safe to re-run if it fails)
#   2  LAW 5: the build document leaves research_outputs/ for exchange/reports/ (sha checked across the copy);
#      the draft's removal is committed on its own, since publish() may stage exchange/** only; pushed
#   3  the append's stamp is filled AFTER the push ("N tierc11 commits, M on a remote") and F-LAR11 --stamped
#      re-certifies it
#   4  the append goes onto exchange/status/LEDGER_APOLLO.md (the commissioning lane's ledger, CONVENTIONS §3.1)
#   5  the non-exchange residue (the stamped append + its certificate) is committed on its own
#   6  publish(): stages exchange/** only, guard-checks the index, commits and pushes (CONVENTIONS §3.4) —
#      and the push result is STATED
#   7  bright paths, and the final line
# Usage:  bash research_outputs/tierc11/close/close_acts.sh [--check]      (--check runs step 0 only and changes nothing)
# Nothing here deletes evidence, touches the live cache, or re-scores anything.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

PY="$HOME/venvs/naiad/bin/python"
export NAIAD_CACHE_DIR="$HOME/.cache/naiad/snapshots/tc11_20260925" PYTHONDONTWRITEBYTECODE=1
BR=v12-v1-census
DRAFT=research_outputs/tierc11/BUILD_DRAFT.md
DOC=exchange/reports/BUILD_2026-09-24_TIERC11_EVENTS.md
APP=research_outputs/tierc11/LEDGER_APOLLO_APPEND.md
LAR=research_outputs/tierc11/close/FIXTURES_CLOSE_LEDGER_STAMPED.txt
LEDGER=exchange/status/LEDGER_APOLLO.md
FIXT=scripts/tierc11_close_fixtures.py
TC10_DOC=exchange/reports/BUILD_2026-09-21_TIERC10_UNSEEN_RANGES.md
TC10_ACTS=research_outputs/tierc10/close/close_acts.sh
TRAILER="Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>"
SOURCES=("research_outputs/tierc11/BUILD_DRAFT.md" "research_outputs/tierc11/LEDGER_APOLLO_APPEND.md" "research_outputs/tierc11/close/S5_FINDINGS_NOT_FIXED.json" "research_outputs/tierc11/close/S5_FINDINGS_NOT_FIXED.md" "research_outputs/tierc11/close/BOX_COST.md" "research_outputs/tierc11/close/BOX_COST.json" "research_outputs/tierc11/close/TRACES.json" "research_outputs/tierc11/close/close_acts.sh" "research_outputs/tierc11/close/COMPUTE_LEDGER.json" "research_outputs/tierc11/close/TC11_FIX_VERIFY.json" "research_outputs/tierc11/close/FIXTURES_CLOSE.txt" "scripts/tierc11_close.py" "scripts/tierc11_close_fixtures.py" "research_outputs/tierc11/review/attest/fix-head.json")

say()  { printf '\n\033[1;36m== %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mSTOPPED at step %s: %s\033[0m\n' "$STEP" "$*"; exit 1; }
sha()  { shasum -a 256 "$1" | cut -c1-64; }

STEP=0; say "0 · preconditions"
[ "$(git rev-parse --abbrev-ref HEAD)" = "$BR" ] || die "not on $BR"
if [ ! -f "$TC10_DOC" ] || ! grep -qE '^=== STATUS_APOLLO — [0-9]{4}-[0-9]{2}-[0-9]{2} — TIER-C10 · ' "$LEDGER"; then
  die "run $TC10_ACTS first (the ledger keeps tier order)"
fi
git ls-files --error-unmatch -- "$TC10_DOC" >/dev/null 2>&1 || die "TC10's CLOSE did not finish: $TC10_DOC is not tracked (TC10's publish() adds it) — see FN-M-TC10-ACTS-IGNORED: TC10's step-6 'git add' exits 1 on paths under .gitignore:263 without -f; finish TC10's steps by hand, then re-run this"
git diff --quiet HEAD -- "$LEDGER" || die "TC10's CLOSE did not finish: $LEDGER differs from HEAD (TC10's block appended, not committed) — see FN-M-TC10-ACTS-IGNORED; finish TC10's steps by hand, then re-run this"
git diff --cached --quiet || die "the index is not clean"
for f in "${SOURCES[@]}" "$LEDGER"; do [ -f "$f" ] || die "missing $f"; done
for f in "${SOURCES[@]}"; do
  git ls-files --error-unmatch -- "$f" >/dev/null 2>&1 || die "$f is not committed (the CLOSE commit adds the CLOSE files first)"
  git diff --quiet HEAD -- "$f" || die "$f differs from HEAD (commit it first)"
done
[ ! -e "$DOC" ] || die "$DOC already exists"
if grep -qE '^=== STATUS_APOLLO — [0-9]{4}-[0-9]{2}-[0-9]{2} — TIER-C11 · ' "$LEDGER"; then die "$LEDGER already carries a TIER-C11 block"; fi
grep -q '⟦STAMP AT CLOSE' "$APP" || die "the append's stamp is not pending"
LARTMP="$(mktemp -d)"
"$PY" "$FIXT" F-LAR11 --root="$LARTMP" > /dev/null || die "F-LAR11 does not certify the pre-stamp append as the sources stand now (transcript $LARTMP/FIXTURES_CLOSE_partial.txt) — nothing was pushed; re-run the generator and the close suite, commit, then re-run this"
rm -rf "$LARTMP"
echo "ok · HEAD $(git rev-parse --short HEAD) · origin/$BR $(git rev-parse --short "origin/$BR") · F-LAR11 GREEN on the pre-stamp append"
if [ "${1:-}" = "--check" ]; then say "--check: step 0 passed; nothing was changed"; exit 0; fi

STEP=1; say "1 · push the committed work (nothing has changed yet; safe to re-run if this fails)"
git push origin "$BR" || die "the push failed — nothing has changed; fix the remote and re-run"
git fetch -q origin
[ "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$BR")" ] || die "origin/$BR does not equal HEAD after the push"
echo "PUSHED · origin/$BR = $(git rev-parse --short HEAD)"

STEP=2; say "2 · LAW 5: the build document moves to exchange/reports/, and that commit is pushed"
a=$(sha "$DRAFT"); cp "$DRAFT" "$DOC"; b=$(sha "$DOC")
[ "$a" = "$b" ] || die "sha changed across the copy ($a vs $b)"
git rm -q "$DRAFT"
git commit -q -m "tierc11(CLOSE): LAW 5 — the build document leaves research_outputs/ for $DOC

The draft's removal is committed on its own because publish() may stage exchange/** only; the
document itself enters the record through publish(). sha256 across the move: $b.

$TRAILER"
echo "moved · sha256 $b · $(wc -c < "$DOC" | tr -d ' ') B"
git push origin "$BR" || die "the move is committed locally ($(git rev-parse --short HEAD)) but did not push; run 'git push origin $BR', then run steps 3-7 by hand from this file"
git fetch -q origin
[ "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$BR")" ] || die "origin/$BR does not equal HEAD after the second push"
echo "PUSHED · origin/$BR = $(git rev-parse --short HEAD)"

STEP=3; say "3 · stamp the append after the push, then re-certify it (F-LAR11 --stamped)"
"$PY" - <<'PYEOF'
import re, subprocess
p = "research_outputs/tierc11/LEDGER_APOLLO_APPEND.md"
def g(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True, check=True).stdout
tc = [l.split("\t", 1)[0] for l in g("log", "--format=%H%x09%s", "HEAD").splitlines()
      if l.split("\t", 1)[-1].startswith("tierc11(")]
off = set(g("rev-list", "HEAD", "--not", "--remotes").split())
n, m = len(tc), sum(1 for h in tc if h not in off)
s = open(p, encoding="utf-8").read()
new, k = re.subn(r"⟦STAMP AT CLOSE[^⟧\n]*⟧", f"{n} tierc11 commits, {m} on a remote", s, count=1)
if k != 1:
    raise SystemExit("no pending stamp found")
open(p, "w", encoding="utf-8").write(new)
print(f"stamp · {n} tierc11 commits, {m} on a remote")
PYEOF
"$PY" "$FIXT" F-LAR11 --stamped > /dev/null || die "F-LAR11 does not certify the stamped append — steps 1-2 are pushed; nothing was appended; the stamp stays filled in $APP for inspection. To resume: 'git checkout -- $APP' (the pending stamp back), fix the cause, then run steps 3-7 by hand from this file (re-running the script stops at step 0: the draft has moved)"
tail -1 "$LAR" | cut -c1-60

STEP=4; say "4 · append to $LEDGER"
before=$(wc -l < "$LEDGER" | tr -d ' ')
cat "$APP" >> "$LEDGER"
after=$(wc -l < "$LEDGER" | tr -d ' ')
echo "appended · $before -> $after lines · $(wc -c < "$LEDGER" | tr -d ' ') B"

STEP=5; say "5 · commit the non-exchange residue"
git add -- "$APP" "$LAR"
git commit -q -m "tierc11(CLOSE): the append stamped after the push and re-certified (F-LAR11 --stamped)

$TRAILER"
echo "committed $(git rev-parse --short HEAD)"

STEP=6; say "6 · publish exchange/** (CONVENTIONS §3.4) — the push result is STATED"
if "$PY" -c "import sys; from pathlib import Path; R=Path('.').resolve(); sys.path.insert(0,str(R/'scripts')); import publish_exchange as p; r=p.publish(R,'$(date +%F)'); print(r['status'], r['commit'], r['pushed'], r['offenders']); sys.exit(0 if r['status']=='PUBLISHED' and r['pushed'] else 1)"; then
  printf '\n\033[1;32mPUSH RESULT: SUCCEEDED — publish() reported PUBLISHED and pushed; origin/%s = %s\033[0m\n' "$BR" "$(git rev-parse --short "origin/$BR")"
else
  die "PUSH RESULT: FAILED — publish() did not report PUBLISHED + pushed (see its lines above); the local commits stay, nothing was lost"
fi

STEP=7; say "7 · bright paths"
printf '\033[1;33m%s\033[0m\n' \
  "$DOC" \
  "$LEDGER  (TC11 STATUS appended)" \
  "exchange/queue/2026-09-24_TC11_APOLLO.md" \
  "research_outputs/tierc11/close/S5_FINDINGS_NOT_FIXED.md" \
  "research_outputs/tierc11/close/BOX_COST.md" \
  "research_outputs/tierc11/PROGRESS.json  (CLOSE still to be recorded by the builder)" \
  "origin/$BR = $(git rev-parse --short "origin/$BR")"
printf '\n\033[1;32mOperator: click Sync now.\033[0m\n'
